#### 在JS中处理异步的几种方式

1. 纯粹callback回调   问题：主要是代码风格的问题，如 回调地狱  剥夺函数return能力
2. promise  解决问题：代码风格   多个异步等待合并 等功能性作用  不需要层层传递callback
3. aync await



#### 把 promise 理解为对象

把 promise 理解为对象，而不是函数。

对象可以保存状态，函数一旦被调用，结果是要马上返回的，不能把结果状态保持在函数内部。



promise 用对象的形式保存了异步调用的结果，而promise本身作为一个对象，可以赋值给一个变量，而这个变量可以在代码中到处传递，此时不需要附加回调函数。一直到想从 promise 中取异步调用的结果时，才需要附加这个回调函数。

#### promise 基本使用格式

```js
const promise = new Promise((resolve, reject) => {
  wx.getSystemInfo({
    success: res => {
      resolve(res)      // 已成功
    },
    fail: error => {
      reject(error)			// 已失败
    }
  })
})

promise.then(
  (res) => {				// 这里接收到的res 就是 resolve(res)保存的res
    console.log(res)
  },
  (error) => {
    console.log(error)  // reject(error) 保存的error
  })
```

**代码简化**

```js
const promise = new Promise((resolve, reject) => {
  wx.getSystemInfo({
    success: res => resolve(res),
    fail: error => reject(error)
  })
})

promise.then(
  res => console.log(res),
  error => console.log(error)
)
```

#### promise 三种状态

pending fulfilled rejected  =>   进行中，已成功，已失败

**pending**    new Promise之后，状态就变成pending

```js
const promise = new Promise((resolve, reject) => {})
```

**fulfilled**    在调用请求数据api的成功回调中 修改promise状态，并传入请求回来的数据res。**resolve(res)**

```js
wx.getSystemInfo({
  success: res => {
    resolve(res)      // 已成功
  },
```

**rejected**  在调用请求数据失败的回调中，修改promise状态，并传入error。**reject(error)**

```js
wx.getSystemInfo({
  success: res => { },
  
  fail: error => {
    reject(error)			// 已失败
  }
})
```

#### 利用promise变量 .then 随时拿到异步回调结果

promise.then 的两个回调函数不是必须要填写，需要获取哪个结果，就填写哪个。

```js
promise.then(
  (res) => {				// 这里接收到的res 就是 resolve(res)保存的res
  console.log(res)
},
  (error) => {
  console.log(error)  // reject(error) 保存的error
})
```